### ISSUE TITLE
Look in to erratic coding site behavior

### ISSUE THREAD

**Issue by tjakester** [chicago-justice-project/chicago-justice#28]
I guess one of our coders is having problems with he cite. I have tried repeatedly to log in with the admin credentials and I have had varying degrees of success. Sometimes I get a failure message and sometimes it let’s me log in - all with the same credentials.

**Comment by meshulam** [comment]
@tjakester I just deployed a fix so that any logged in user can code articles. There was a bug where it would take non-admins to the summary view instead of the full one.

Can you tell me the error message you're getting? I see some performance issues that I will continue to look into, not sure if that's related.

**Comment by tjakester** [comment]
@meshulam The error message I was getting when I tried to log in and it failed, which it would not do every time it would occur erratically was that my access was forbidden.

**Comment by meshulam** [comment]
Closing this issue since I think I fixed the problem the coder ran into. If you continue to experience login errors, please open a new issue with the exact message or a screenshot of what you see.
